spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "498039010006-eq0absoe0seofnaan6dcka2vb7iis853.apps.googleusercontent.com"
            clientSecret: "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"
            scope:
              - email
              - profile
            redirect-uri: "https://server.wanderhub.kro.kr/login/oauth2/code/google"
          kakao:
            clientId: "e9055e2756feca8bfdb492cd8e4ec1b5"
            client-secret: "cjgvxAr0ZgEIq2CXYkpKxO049AXC1nYS"
            redirect-uri: "https://server.wanderhub.kro.kr/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id