spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: $(echo $G_CLIENT_ID)
            clientSecret: $(echo $G_CLIENT_SECRET)
            scope:
              - email
              - profile
            redirect-uri: "https://server.wanderhub.kro.kr/login/oauth2/code/google"
          kakao:
            clientId: $(echo $K_CLIENT_ID)
            client-secret: $(echo $K_CLIENT_SECRET)
            redirect-uri: "https://server.wanderhub.kro.kr/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id